// ---------------------------------------------------------------- //
// This file is autogenerated by pioasm version 2.3.0; do not edit! //
// ---------------------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

#ifdef __cpp_constexpr
#define __pio_const constexpr
#else
#define __pio_const const
#endif

// ------- //
// i2s_out //
// ------- //

#define i2s_out_wrap_target 0
#define i2s_out_wrap 7
#define i2s_out_pio_version 1

#define i2s_out_offset_entry_point 7u

static __pio_const uint16_t i2s_out_program_instructions[] = {
            //     .wrap_target
    0x6801, //  0: out    pins, 1         side 1
    0x1840, //  1: jmp    x--, 0          side 3
    0x6001, //  2: out    pins, 1         side 0
    0xf02e, //  3: set    x, 14           side 2
    0x6001, //  4: out    pins, 1         side 0
    0x1044, //  5: jmp    x--, 4          side 2
    0x6801, //  6: out    pins, 1         side 1
    0xf82e, //  7: set    x, 14           side 3
            //     .wrap
};

#if !PICO_NO_HARDWARE
static __pio_const struct pio_program i2s_out_program = {
    .instructions = i2s_out_program_instructions,
    .length = 8,
    .origin = -1,
    .pio_version = i2s_out_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config i2s_out_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + i2s_out_wrap_target, offset + i2s_out_wrap);
    sm_config_set_sideset(&c, 2, false, false);
    return c;
}

// data_pin: DOUT (GPIO20, DSDIN on the ES8311 - see sound.c). lrck_pin_base:
// the LOWER of the two side-set pins, i.e. LRCK (GPIO23); BCLK (GPIO24) is
// lrck_pin_base + 1, fixed by the .pio program above, not a parameter.
static inline void i2s_out_program_init(PIO pio, uint sm, uint offset, uint data_pin, uint lrck_pin_base) {
    pio_sm_config c = i2s_out_program_get_default_config(offset);
    sm_config_set_out_pins(&c, data_pin, 1);
    sm_config_set_sideset_pins(&c, lrck_pin_base);
    sm_config_set_out_shift(&c, false, true, 32);
    sm_config_set_fifo_join(&c, PIO_FIFO_JOIN_TX);
    pio_sm_init(pio, sm, offset, &c);
    uint32_t pin_mask = (1u << data_pin) | (3u << lrck_pin_base);
    pio_sm_set_pindirs_with_mask(pio, sm, pin_mask, pin_mask);
    pio_sm_set_pins(pio, sm, 0); // clear pins before the SM starts driving them
    pio_gpio_init(pio, data_pin);
    pio_gpio_init(pio, lrck_pin_base);
    pio_gpio_init(pio, lrck_pin_base + 1);
    // Jump straight to entry_point: the two "set x, 14" instructions above it
    // are only ever reached via fallthrough from inside the program's own
    // loops, never as a valid starting state (matches pico-extras' own
    // audio_i2s_program_init(), which does the identical jmp for the same
    // reason: pio_sm_init() otherwise starts execution at offset 0).
    pio_sm_exec(pio, sm, pio_encode_jmp(offset + i2s_out_offset_entry_point));
}

#endif

